
features_to_index = {
    "RefAllel":5, 
    "VarAllel": 6, 
    "TotalPosCov":7, 
    "positioncoverage" : 8,
    "refForwardcoverage" : 9,
    "refReversecoverage" : 10,
    "varsCountOnForward" : 11, 
    "VarsCountOnReverse" : 12,
    "genotype" : 13,
    "frequency" : 14,
    "strandbiasflag" : 15,
    "meanPosition" : 16,
    "pstd" : 17,
    "meanQuality" : 18,
    "qstd" : 19, 
    "pvalue" : 20,
    "ratio" : 21,
    "mapq" : 22,
    "qratio" : 23,
    "higreq" : 24, 
    "extrafreq" : 25,
    "shift3" : 26,
    "msi" : 27,
    "msint" : 28,
    "nm" : 29,
    "hicnt" : 30,
    "hicov" : 31,
    "leftSequence" : 32,
    "rightSequence" : 33,
    "region" : 34,
    "varType" : 35,
    "duprate" : 36
    }

All_features = [
    "RefAllel", 
    "VarAllel", 
    "TotalPosCov", 
    "positioncoverage",
    "refForwardcoverage",
    "refReversecoverage",
    "varsCountOnForward", 
    "VarsCountOnReverse",
    "genotype",
    "frequency",
    "strandbiasflag",
    "meanPosition",
    "pstd",
    "meanQuality",
    "qstd", 
    "pvalue",
    "ratio",
    "mapq",
    "qratio",
    "higreq", 
    "extrafreq",
    "shift3",
    "msi",
    "msint",
    "nm",
    "hicnt",
    "hicov",
    "leftSequence",
    "rightSequence",
    "region",
    "varType",
    "duprate"
    ]
fvc_selected_features = [
     "TotalPosCov", 
     "positioncoverage",
     "refForwardcoverage",
     "refReversecoverage",
     "varsCountOnForward", 
     "VarsCountOnReverse",
    "frequency",
     "meanPosition",
     "pstd",
     "meanQuality",
     "pvalue",
     "ratio",
    "mapq",
     "qratio",
     "higreq", 
    "shift3",
    "msi",
     "msint",
    "nm",
     "hicnt",
     "hicov",
    ]
